### ISSUE TITLE
My results in open-domain QA are much lower using the given checkpoint for CEPE-LLaMA-2-7B. Could you provide some insights into the potential causes for this decline?

### ISSUE THREAD

**Issue by sunnynexus** [princeton-nlp/CEPE#1]
I'm curious about the discrepancies between my results (in red font) and the results presented in your paper (in black font), both obtained using the default parameters with the run_qa.sh script. 

<img width="1145" alt="image" src="https://github.com/princeton-nlp/CEPE/assets/154594175/bdd27233-9fdc-4423-ab32-af87a97cc53f">

Could there be any potential errors on my end that could explain these differences?

**Comment by howard-yen** [comment]
Hi, thanks for your interest in our work. 
For CEPE at k = 10, we only use and put all the passages in the decoder model, which should match the results for LLaMA-2. There might have been a mistake in the config file, which I will look into.
Are you also using the QA files from the google drive?

**Comment by sunnynexus** [comment]
I have tried running it multiple times, but the results are still not superior to the basic llama-2-7b model.
